### PR TITLE
Don't ask me why this works, but it works - LinkedIn URLs now operati…

### PR DESCRIPTION
**Pull request by laurenceday**
…onal

### CODE REVIEW

**Review by mustafasaifee42 — CHANGES_REQUESTED** [review]
The changes on team card wont work:
 instead of 
`{props.linkedin ? (
        <a href = {props.linkedinURL} target="_blank">
          <LinkedIn src={LinkedinLogo} alt="Linkedin Icon" />
        ) : null}
        </a>) : null}`
you might want to do:
`{props.linkedin ? (
         <>
        <a href = {props.linkedinURL} target="_blank">
          <LinkedIn src={LinkedinLogo} alt="Linkedin Icon" />
        </a>
         </>) : null}`

**Comment by laurenceday** [comment]
I am _so_ sorry that you're looking at this at 03:30 - I was kinda hoping you wouldn't get pings on this.

Is my lack of front-end showing?

When you get a chance, can I pick your brain about sorting out domain masking and porting this CI over to our ArboreumDev team repo so you don't have to get dinged like a bell every time I try and do stupid stuff?

**Comment by mustafasaifee42** [comment]
> I am _so_ sorry that you're looking at this at 03:30 - I was kinda hoping you wouldn't get pings on this.
> 
> Is my lack of front-end showing?
> 
> When you get a chance, can I pick your brain about sorting out domain masking and porting this CI over to our ArboreumDev team repo so you don't have to get dinged like a bell every time I try and do stupid stuff?

No issues! I will anyways try to merge them tomorrow

 deploy will fail because the LinkedinURL you have made the type `string` in one file and `undefined` or `string` in another

so either have this type everywhere `LinkedinURL: string` or `LinkedinURL?:string` but dont mix them

**Comment by laurenceday** [comment]
Yeah I'm just going to make it a mandatory field, and our one exception can deal with having Google.com as his assigned URL.

I owe you a beer or sin of your choice - I'll have to grab your address when this is all done with ;)

**Comment by laurenceday** [comment]
WELL THAT TOOK LONG ENOUGH

I'm just going to point the site at the deploy preview for now and take my victory where I can

Thanks for watching me struggle like a wean - g'night!

**Pull request merged**
